# This file was generated by GoReleaser. DO NOT EDIT.
class Bloyd < Formula
  desc "Personal floydhub-like cli"
  homepage "https://github.com/u0xy/bloyd"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/u0xy/bloyd/releases/download/v0.2.1/bloyd_0.2.1_Darwin_x86_64.tar.gz"
    sha256 "78d6ad550f779270dc8812de707909ab9534d7cece2ee006325c216483afae05"
  elsif OS.linux?
  end

  def install
    bin.install "bloyd"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/bloyd --version"
  end
end
