# This file was generated by GoReleaser. DO NOT EDIT.
class Bloyd < Formula
  desc "Personal floydhub-like cli"
  homepage "https://github.com/u0xy/bloyd"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/u0xy/bloyd/releases/download/v0.3.0/bloyd_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "41efbadecbc7a9b57e42e19a3b41c21781736f37ec44ff0efdc83d8315c9c71b"
  elsif OS.linux?
  end

  def install
    bin.install "bloyd"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/bloyd --version"
  end
end
